### ISSUE TITLE
Timestamped 버그

### ISSUE THREAD

**Issue by lgkrwnsdll** [innovation-final/Backend#11]
**Describe the bug**
타임스탬프 정보가 DB에 저장은 잘 되는데, 조회할 때는 9시간씩 빠르게 조회되는 버그

**To Reproduce**
인텔리제이 RDS 테이블과 hakjoonkim.shop/api/post로 get 요청 결과 비교해보시면 날짜 정보가 다릅니다

**Expected behavior**
날짜 정보 일치시키기

**Comment by Meanz12** [comment]
RDS time_zone을 Asia/Seoul로 하여도 변동없음.

**Comment by lgkrwnsdll** [comment]
EC2 timezone KST로 변경해도 해결 안됨

**Comment by lgkrwnsdll** [comment]
EC2 locale 설정까지 하고 재부팅해도 해결 안됨

**Comment by lgkrwnsdll** [comment]
`@EnableJpaAuditing
@SpringBootApplication
public class StockStockApplication {

    @PostConstruct
    void started() {
        TimeZone.setDefault(TimeZone.getTimeZone("Asia/Seoul"));
    }

    public static void main(String[] args) {
        SpringApplication.run(StockStockApplication.class, args);
    }

}`
